### ISSUE TITLE
Can ast be converted to Swift?

### ISSUE THREAD

**Issue by LuckyRoc** [kishikawakatsumi/swift-ast-explorer#1]

**Comment by kishikawakatsumi** [comment]
@ChengRuipeng Not sure what you mean by "converted to Swift," can you elaborate?

**Comment by ChengRuipeng** [comment]
> @ChengRuipeng Not sure what you mean by "converted to Swift," can you elaborate?

I can convert Swift to AST by 'swift-ast-explorer',  can I convert AST back to Swift?

**Comment by kishikawakatsumi** [comment]
@ChengRuipeng No you can't. `'swift-ast-explorer'` converts AST to HTML for visualization. It is not reversible. 

I recommend to use SwiftSyntax directly. SwiftSyntax is created for making it easier to rewrite Swift AST.
